#############################################################################
# Makefile for building: AdAndCrapBlock
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mi. Jul 10 20:40:36 2013
# Project:  ../AdAndCrapBlock/AdAndCrapBlock.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../AdAndCrapBlock/AdAndCrapBlock.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../AdAndCrapBlock -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I../AdAndCrapBlock -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../AdAndCrapBlock/main.cpp \
		../AdAndCrapBlock/mainwindow.cpp \
		../AdAndCrapBlock/downloader.cpp \
		../AdAndCrapBlock/parserthread.cpp \
		../AdAndCrapBlock/processsimthread.cpp moc_mainwindow.cpp \
		moc_downloader.cpp \
		moc_parserthread.cpp \
		moc_processsimthread.cpp \
		qrc_AppResources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		downloader.o \
		parserthread.o \
		processsimthread.o \
		moc_mainwindow.o \
		moc_downloader.o \
		moc_parserthread.o \
		moc_processsimthread.o \
		qrc_AppResources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../AdAndCrapBlock/AdAndCrapBlock.pro
QMAKE_TARGET  = AdAndCrapBlock
DESTDIR       = 
TARGET        = AdAndCrapBlock

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../AdAndCrapBlock/AdAndCrapBlock.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../AdAndCrapBlock/AdAndCrapBlock.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../AdAndCrapBlock/AdAndCrapBlock.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AdAndCrapBlock1.0.0 || $(MKDIR) .tmp/AdAndCrapBlock1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AdAndCrapBlock1.0.0/ && $(COPY_FILE) --parents ../AdAndCrapBlock/mainwindow.h ../AdAndCrapBlock/downloader.h ../AdAndCrapBlock/parserthread.h ../AdAndCrapBlock/processsimthread.h .tmp/AdAndCrapBlock1.0.0/ && $(COPY_FILE) --parents ../AdAndCrapBlock/AppResources.qrc .tmp/AdAndCrapBlock1.0.0/ && $(COPY_FILE) --parents ../AdAndCrapBlock/main.cpp ../AdAndCrapBlock/mainwindow.cpp ../AdAndCrapBlock/downloader.cpp ../AdAndCrapBlock/parserthread.cpp ../AdAndCrapBlock/processsimthread.cpp .tmp/AdAndCrapBlock1.0.0/ && $(COPY_FILE) --parents ../AdAndCrapBlock/mainwindow.ui .tmp/AdAndCrapBlock1.0.0/ && (cd `dirname .tmp/AdAndCrapBlock1.0.0` && $(TAR) AdAndCrapBlock1.0.0.tar AdAndCrapBlock1.0.0 && $(COMPRESS) AdAndCrapBlock1.0.0.tar) && $(MOVE) `dirname .tmp/AdAndCrapBlock1.0.0`/AdAndCrapBlock1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AdAndCrapBlock1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_downloader.cpp moc_parserthread.cpp moc_processsimthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_downloader.cpp moc_parserthread.cpp moc_processsimthread.cpp
moc_mainwindow.cpp: ../AdAndCrapBlock/downloader.h \
		ui_mainwindow.h \
		../AdAndCrapBlock/processsimthread.h \
		../AdAndCrapBlock/parserthread.h \
		../AdAndCrapBlock/mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ../AdAndCrapBlock/mainwindow.h -o moc_mainwindow.cpp

moc_downloader.cpp: ../AdAndCrapBlock/downloader.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ../AdAndCrapBlock/downloader.h -o moc_downloader.cpp

moc_parserthread.cpp: ../AdAndCrapBlock/parserthread.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ../AdAndCrapBlock/parserthread.h -o moc_parserthread.cpp

moc_processsimthread.cpp: ../AdAndCrapBlock/processsimthread.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ../AdAndCrapBlock/processsimthread.h -o moc_processsimthread.cpp

compiler_rcc_make_all: qrc_AppResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_AppResources.cpp
qrc_AppResources.cpp: ../AdAndCrapBlock/AppResources.qrc \
		../AdAndCrapBlock/icons/aacblock_middle.png \
		../AdAndCrapBlock/icons/aacblock_small.png \
		../AdAndCrapBlock/icons/aacblock_big.png
	/usr/lib/qt4/bin/rcc -name AppResources ../AdAndCrapBlock/AppResources.qrc -o qrc_AppResources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../AdAndCrapBlock/mainwindow.ui
	/usr/lib/qt4/bin/uic ../AdAndCrapBlock/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: ../AdAndCrapBlock/main.cpp ../AdAndCrapBlock/mainwindow.h \
		../AdAndCrapBlock/downloader.h \
		ui_mainwindow.h \
		../AdAndCrapBlock/processsimthread.h \
		../AdAndCrapBlock/parserthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../AdAndCrapBlock/main.cpp

mainwindow.o: ../AdAndCrapBlock/mainwindow.cpp ../AdAndCrapBlock/mainwindow.h \
		../AdAndCrapBlock/downloader.h \
		ui_mainwindow.h \
		../AdAndCrapBlock/processsimthread.h \
		../AdAndCrapBlock/parserthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../AdAndCrapBlock/mainwindow.cpp

downloader.o: ../AdAndCrapBlock/downloader.cpp ../AdAndCrapBlock/downloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloader.o ../AdAndCrapBlock/downloader.cpp

parserthread.o: ../AdAndCrapBlock/parserthread.cpp ../AdAndCrapBlock/parserthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parserthread.o ../AdAndCrapBlock/parserthread.cpp

processsimthread.o: ../AdAndCrapBlock/processsimthread.cpp ../AdAndCrapBlock/processsimthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processsimthread.o ../AdAndCrapBlock/processsimthread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_downloader.o: moc_downloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloader.o moc_downloader.cpp

moc_parserthread.o: moc_parserthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parserthread.o moc_parserthread.cpp

moc_processsimthread.o: moc_processsimthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processsimthread.o moc_processsimthread.cpp

qrc_AppResources.o: qrc_AppResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_AppResources.o qrc_AppResources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

